spring:
  datasource:
    username: root
    password: 12345678
    url: jdbc:mysql://localhost:3306/template
  data:
    # 配置redis
    redis:
      host: localhost
      port: 6379
      database: 0
security:
  aes:
    key: 7f9a2b4c8d6e1f3a